openapi: 3.2.0
info:
  description: 'The setlist.fm API has been designed to give you easy access to setlist data in order to build fancy websites and

    other applications.'
  version: '1.0'
  title: setlist.fm /1.0/user/{user Id} API
servers:
- url: /rest
tags:
- name: /1.0/user/{userId}
paths:
  /1.0/user/{userId}:
    get:
      tags:
      - /1.0/user/{userId}
      summary: Get a user by userId
      description: 'Get a user by userId. (deprecated)


        Note: This endpoint always returns a result, even if the user doesn''t exist'
      operationId: resource__1.0_user__userId__getUser_GET
      parameters:
      - name: userId
        in: path
        required: true
        description: the user's userId
        schema:
          type: string
      responses:
        '200':
          headers: {}
          description: Success
          content:
            application/xml:
              schema:
                description: ''
                $ref: '#/components/schemas/json_User'
            application/json:
              schema:
                description: ''
                $ref: '#/components/schemas/json_User'
              example:
                userId: '...'
                fullname: '...'
                lastFm: '...'
                mySpace: '...'
                twitter: '...'
                flickr: '...'
                website: '...'
                about: '...'
                url: '...'
components:
  schemas:
    json_User:
      type: object
      title: user
      properties:
        userId:
          description: ''
          type: string
        fullname:
          description: never set (deprecated)
          type: string
        lastFm:
          description: never set (deprecated)
          type: string
        mySpace:
          description: never set (deprecated)
          type: string
        twitter:
          description: never set (deprecated)
          type: string
        flickr:
          description: never set (deprecated)
          type: string
        website:
          description: never set (deprecated)
          type: string
        about:
          description: never set (deprecated)
          type: string
        url:
          description: ''
          type: string
      example:
        userId: '...'
        fullname: '...'
        lastFm: '...'
        mySpace: '...'
        twitter: '...'
        flickr: '...'
        website: '...'
        about: '...'
        url: '...'
      description: This class represents a user.
